SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO AS FI2
    JOIN FISH_NAME_INFO AS FNI2 ON FI2.FISH_TYPE = FNI2.FISH_TYPE
    WHERE FNI2.FISH_NAME = FNI.FISH_NAME
)